---
- name: downloading RVM installer
  get_url:
    url: "{{rvm.url}}"
    dest: "{{rvm.temp_installer_path}}"

- name: set executable RVM installer
  file:
    path: "{{rvm.temp_installer_path}}"
    mode: 0755

- name: installing RVM
  command: "{{rvm.temp_installer_path}} --path {{rvm.root}} stable"

- name: removing RVM installer
  file:
    path: "{{rvm.temp_installer_path}}"
    state: absent

- name: add user {{ ansible_ssh_user }} to rvm group
  action: user name={{ ansible_ssh_user }} groups=rvm append=yes

- name: setting RVM autolibs on
  command: "{{rvm.root}}/bin/rvm autolibs 3"
