---
- name: Install Ruby
  apt: pkg=ruby update-cache=yes
  sudo: yes
  tags: ruby

- name: Install compass gem
  gem: name=compass
  sudo: yes
  tags: ruby

- name: Install bundler # Something funky going on here. Bundler isn't installing.
  gem: name=bundler
  sudo: yes
  tags: ruby

