---
- name: Install Ruby
  apt: pkg=ruby2.0 update-cache=yes
  sudo: yes
  tags: ruby

- name: Install Ruby-dev (for building native extensions)
  apt: pkg=ruby2.0-dev update-cache=yes
  sudo: yes
  tags: ruby

- name: Install compass gem
  gem: name=compass
  sudo: yes
  tags: ruby

- name: Install bundler # Something funky going on here. Bundler isn't installing.
  gem: name=bundler
  sudo: yes
  tags: ruby

