# playbook.yml
---
- hosts: all

  vars_files:
  - vars/elasticsearch.yml

  roles:
    - oh-my-zsh
    - { role: altermn.rvm, sudo: yes }
    - { role: crushlovely.imagemagick }
    - nodejs
    - { role: gpstathis.elasticsearch, sudo: yes }
    - janus
    - byobu
    - grunt
    - bower
    - coffee
    - yo

